---
version: "3.7"

networks:
    default:

volumes:
    postgres_data:
    firebase_data:

services:
    newsletter-assignment:
        container_name: newsletter-assignment
        init: true
        build:
            context: .
            target: development
            args:
                PROJECT_ROOT: "/go/src/newsletter-assignment"
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            CONFIG_HTTP_PORT: 8080
            CONFIG_APP_ENV: dev
            CONFIG_APP_NAME: newsletter-assignment
            CONFIG_JWT_SECRET: "0zinGG2-iDxTjLCmd4oqw29tBlhbzNITfUO-pIdyQcc="
            CONFIG_CORS_ALLOWED_ORIGINS: http://localhost
            CONFIG_CORS_ALLOWED_HEADERS: authorization;content-type
            CONFIG_FIREBASE_HOST: "http://127.0.0.1"
            CONFIG_FIREBASE_PORT: 9000
            CONFIG_FIREBASE_PROJECT_ID: "strv-go-newsletter-javor-jiri"
            CONFIG_FIREBASE_SERVICE_ACCOUNT_KEY: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3Rydi1nby1uZXdzbGV0dGVyLWphdm9yLWppcmkiLAogICJwcml2YXRlX2tleV9pZCI6ICJtb2NrLWtleS1pZC0xMjM0NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFDOVBjMEFBQUFBQUFBPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLXh4eHh4QGRlbW8tcHJvamVjdC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMjM0NTY3ODkiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLXh4eHh4JTQwZGVtby1wcm9qZWN0LmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9"
            CONFIG_TIMEZONE: Europe/Prague

            # Logger config
            CONFIG_LOG_LEVEL: debug
            CONFIG_LOG_DEVEL_MODE: 1

            # Prometheus config
            CONFIG_PROMETHEUS_SUBSYSTEM: newsletter-assignment

            # Postgres config
            CONFIG_POSTGRES_USER: newsletter-assignment
            CONFIG_POSTGRES_PASSWORD: pwd
            CONFIG_POSTGRES_DB: newsletter-assignment
            CONFIG_POSTGRES_HOST: postgres
            CONFIG_POSTGRES_PORT: 5432
            CONFIG_POSTGRES_POOL_HEALTH_CHECK_PERIOD: 5s

        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health/readiness || exit 1"]
            interval: 15s
            timeout: 10s
            retries: 3
        ports:
            - "8080:8080"
        volumes:
            - ".:/go/src/newsletter-assignment/:cached"

    postgres:
        container_name: postgres
        image: "postgres:16-alpine"
        restart: unless-stopped
        environment:
            POSTGRES_DB: newsletter-assignment
            POSTGRES_USER: newsletter-assignment
            POSTGRES_PASSWORD: pwd
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U newsletter-assignment -d newsletter-assignment"]
            interval: 10s
            timeout: 5s
            retries: 5

    firebase-emulators:
        container_name: firebase
        build:
            context: ./firebase
        ports:
            - "9000:9000"  # Realtime Database emulator
            - "4000:4000"  # UI
        volumes:
            - ./firebase/firebase.json:/firebase/firebase.json
            - ./firebase/database.rules.json:/firebase/database.rules.json
            - firebase_data:/firebase/firebase-data
        environment:
            - FIREBASE_DATABASE_EMULATOR_HOST=0.0.0.0:9000
            - FIREBASE_AUTH_EMULATOR_HOST=0.0.0.0:9099
            - FIREBASE_TOKEN=dummy-token
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/.json"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
